prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

branch-protection:
  orgs:
    yufan-org:
      protect: true
      required_status_checks:
        contexts:
        - cla/google
      required_pull_request_reviews:
        required_approving_review_count: 1

plank:
  default_decoration_config:
    utility_images: # using the tag we identified above
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190808-5e69697af"
      initupload: "gcr.io/k8s-prow/initupload:v20190808-5e69697af"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190808-5e69697af"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190808-5e69697af"
    gcs_configuration:
      bucket: om-prow-artifacts # the bucket we just made
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials # the secret we just made

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 30m

tide:
  sync_period: 1m
  queries:
  - orgs:
    - yufan-org
    labels:
    - lgtm
    - approved
    # - "cla: yes"
  merge_method:
    yufan-org: squash
  pr_status_base_url: http://34.98.83.174/pr

periodics:
- interval: 10m
  name: echo-test
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]

postsubmits:
  yufan-org/open-match:
  - name: test-postsubmit
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]

presubmits:
  yufan-org/open-match:
  - name: test-test-test
    decorate: true
    always_run: true
    spec:
      containers:
      - image: gcr.io/open-match-build/open-match-build
        command: ["ls"]
  - name: test-presubmit
    decorate: true
    always_run: true
    spec:
      serviceAccountName: test-ksa
      containers:
      - image: gcr.io/open-match-build/open-match-build
        command: ["gcloud"]
        args: ["auth", "list"]
